Fixed missing .meta files for multiple files
Error: ***has no meta file, but it's in an immutable folder. The asset will be ignored.
Generated .meta files for: composite.png, typewriter.gif, typewrite.png